apiVersion: v1
kind: Pod
metadata:
  name: my-web-app
  labels:
    app: my-web-app
spec:
  containers:
    - name: project-image
      image: elnomanyos2/nginx.project
      imagePullPolicy: IfNotPresent
      ports: 
        - containerPort: 80